# Generated by Django 4.0.2 on 2022-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klienci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='dogs_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='dogs_race',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
