# Generated by Django 4.0.2 on 2022-04-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klienci', '0005_klient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
