# Generated by Django 4.0.2 on 2022-04-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Klienci', '0006_alter_klient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='my_date_field',
        ),
    ]
