# Generated by Django 4.0.2 on 2022-04-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klienci', '0007_remove_klient_my_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='my_date_field',
            field=models.DateTimeField(null=True),
        ),
    ]
