# Generated by Django 4.0.2 on 2022-04-08 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klienci', '0008_klient_my_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='my_date_field',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
