# Generated by Django 4.0.3 on 2022-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_companycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='companycode',
            new_name='kod_kon',
        ),
        migrations.AddField(
            model_name='profile',
            name='aktywny',
            field=models.BooleanField(default=True),
        ),
    ]
