# Generated by Django 4.0.3 on 2022-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_rename_companycode_profile_kod_kon_profile_aktywny'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kod_aktywacyjny',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
